export { default as Error } from "./Error";
export { default as Landing } from "./Landing";
export { default as Login } from "./Login";
export { default as Profile } from "./Profile";
export { default as Register } from "./Register";
export { default as SingleTour } from "./SingleTour";
export { default as Tours } from "./Tours";
export { default as SharedLayout } from "./SharedLayout";
export { default as Chat } from "./Chat";
export { default as NewTour } from "./NewTour";
export { default as DeleteTour } from "./DeleteTour";
export { default as Plans } from "./Plans";
export {default as Checkout} from "./Checkout";